{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.1.8.jar",
          "url": "customtransformplugin-1.1.8.jar",
          "size": 38529,
          "sha512": "995513b62fdbbdf2898d28c2bf5e0050f0a8e3ca8da464ad797613c4de7e4b2e3fcb4904adecfc9c85d3d304a65b71085141c59a1ae56fbb336fbe215578bc8a",
          "sha256": "08484cecb138720f81d83411158b9fcc45ddf46ab539c1b890b933d59623ba60",
          "sha1": "70c9f6b804bee2dd07c9455f357ac6b7462f31c4",
          "md5": "4dddea6c78fa45b967254ff9388035f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.1.8.jar",
          "url": "customtransformplugin-1.1.8.jar",
          "size": 38529,
          "sha512": "995513b62fdbbdf2898d28c2bf5e0050f0a8e3ca8da464ad797613c4de7e4b2e3fcb4904adecfc9c85d3d304a65b71085141c59a1ae56fbb336fbe215578bc8a",
          "sha256": "08484cecb138720f81d83411158b9fcc45ddf46ab539c1b890b933d59623ba60",
          "sha1": "70c9f6b804bee2dd07c9455f357ac6b7462f31c4",
          "md5": "4dddea6c78fa45b967254ff9388035f4"
        }
      ]
    }
  ]
}
