{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dream",
    "module": "customtransformplugin",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.4.1.jar",
          "url": "customtransformplugin-1.4.1.jar",
          "size": 16317,
          "sha512": "dbc51101accd61e3d8afa46531f61e861a0ca5c0ee277901feeaa645369b979fe1d3d9124ba175648cd9940b11cd22f5aa0c21b32b48431b3154718c2ee62b1b",
          "sha256": "a54c9bc36139ecc8144840b01cfd1179761d4593fb30c506db7dce2335f8213c",
          "sha1": "5fd1efddb0a622d629dd641d6373e63cbfb5c9de",
          "md5": "4db05829e1a5d21bc128d77e48c18481"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.4.1.jar",
          "url": "customtransformplugin-1.4.1.jar",
          "size": 16317,
          "sha512": "dbc51101accd61e3d8afa46531f61e861a0ca5c0ee277901feeaa645369b979fe1d3d9124ba175648cd9940b11cd22f5aa0c21b32b48431b3154718c2ee62b1b",
          "sha256": "a54c9bc36139ecc8144840b01cfd1179761d4593fb30c506db7dce2335f8213c",
          "sha1": "5fd1efddb0a622d629dd641d6373e63cbfb5c9de",
          "md5": "4db05829e1a5d21bc128d77e48c18481"
        }
      ]
    }
  ]
}
