{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.1.6.jar",
          "url": "customtransformplugin-1.1.6.jar",
          "size": 37444,
          "sha512": "77e59f96894692c844daa56f2d72c7ff96f0922f1a9457c35dada72b5f8dabee728dfb4e03f01310291702f14b14bb46561c5c808ff5fd80f8d75c4b82ec1b10",
          "sha256": "985341ca96602dbdeec588baa067b0e5f1ff6d6f989c2428f3f2862dcfcc55bb",
          "sha1": "f89c70c6f8dabf0fc6c0596fe8d6357313707bd9",
          "md5": "26cbe767381b4d441acfb11ec2e7bae4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.1.6.jar",
          "url": "customtransformplugin-1.1.6.jar",
          "size": 37444,
          "sha512": "77e59f96894692c844daa56f2d72c7ff96f0922f1a9457c35dada72b5f8dabee728dfb4e03f01310291702f14b14bb46561c5c808ff5fd80f8d75c4b82ec1b10",
          "sha256": "985341ca96602dbdeec588baa067b0e5f1ff6d6f989c2428f3f2862dcfcc55bb",
          "sha1": "f89c70c6f8dabf0fc6c0596fe8d6357313707bd9",
          "md5": "26cbe767381b4d441acfb11ec2e7bae4"
        }
      ]
    }
  ]
}
