{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.0.4.jar",
          "url": "customtransformplugin-1.0.4.jar",
          "size": 34087,
          "sha512": "d0845a949bf28d76e1d2ad4129821f162e72e766510a4b94212d886fe67af04afbda66419e1da2e070d9b6ff3931a0462228755794990b08589d2b75078d764d",
          "sha256": "080ac86e252f0359873038009ac5e7d44d09dc456be4f43ae1b913f4118957fe",
          "sha1": "66db3c859b099afd5f5b6b7746ae168842f4e442",
          "md5": "8a2cc70b7df05eb6d7779f8255a659b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.0.4.jar",
          "url": "customtransformplugin-1.0.4.jar",
          "size": 34087,
          "sha512": "d0845a949bf28d76e1d2ad4129821f162e72e766510a4b94212d886fe67af04afbda66419e1da2e070d9b6ff3931a0462228755794990b08589d2b75078d764d",
          "sha256": "080ac86e252f0359873038009ac5e7d44d09dc456be4f43ae1b913f4118957fe",
          "sha1": "66db3c859b099afd5f5b6b7746ae168842f4e442",
          "md5": "8a2cc70b7df05eb6d7779f8255a659b9"
        }
      ]
    }
  ]
}
