{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dream",
    "module": "customtransformplugin",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.5.0.jar",
          "url": "customtransformplugin-1.5.0.jar",
          "size": 13334,
          "sha512": "189ecf7d97d2832f9175a54013df953e673c70f298fb70fcc4cc408e9798c7b8091e1407cda6cb70232d67717be8499704d6c05e825dba7a260a032725d710e2",
          "sha256": "444324968d1ba0127f573b147cc8e8e2050e199ed0f03ad6053f7f3973113a5f",
          "sha1": "25ac8644979031ede72c9948d9d269137e8e477e",
          "md5": "49a2c1096485cdef011011b930371c01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.5.0.jar",
          "url": "customtransformplugin-1.5.0.jar",
          "size": 13334,
          "sha512": "189ecf7d97d2832f9175a54013df953e673c70f298fb70fcc4cc408e9798c7b8091e1407cda6cb70232d67717be8499704d6c05e825dba7a260a032725d710e2",
          "sha256": "444324968d1ba0127f573b147cc8e8e2050e199ed0f03ad6053f7f3973113a5f",
          "sha1": "25ac8644979031ede72c9948d9d269137e8e477e",
          "md5": "49a2c1096485cdef011011b930371c01"
        }
      ]
    }
  ]
}
