{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dream",
    "module": "customtransformplugin",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.6.8.jar",
          "url": "customtransformplugin-1.6.8.jar",
          "size": 16495,
          "sha512": "62fbee5fbb33078054512474ba02207f591c352188dca43ca1bd07878751268bebd801c4b53bcae83a70c962e871a38ea3d2276c0d9278a150188e2db68d4d16",
          "sha256": "3b3d822c518e1e323b52bbb32614a9d72f09b567e7bfd1f978aa21353c91b3d0",
          "sha1": "715dc3c14ddf571e12e0c0a365fe51c9f8850348",
          "md5": "edabe6e04335528cc9ba6b6187890554"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.6.8.jar",
          "url": "customtransformplugin-1.6.8.jar",
          "size": 16495,
          "sha512": "62fbee5fbb33078054512474ba02207f591c352188dca43ca1bd07878751268bebd801c4b53bcae83a70c962e871a38ea3d2276c0d9278a150188e2db68d4d16",
          "sha256": "3b3d822c518e1e323b52bbb32614a9d72f09b567e7bfd1f978aa21353c91b3d0",
          "sha1": "715dc3c14ddf571e12e0c0a365fe51c9f8850348",
          "md5": "edabe6e04335528cc9ba6b6187890554"
        }
      ]
    }
  ]
}
