{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.0.2.jar",
          "url": "customtransformplugin-1.0.2.jar",
          "size": 33055,
          "sha512": "15ac43ef815cdd44a7eec7865b75ea66bf21633182d74a02a1e0d8cdc15d81fd9184342d64cb80e3f07f319f7447630ac9440af4b6903d1bd577a0405ae7d418",
          "sha256": "3a386229708bc8a9f0beab42539cc1dc50d284dc483c9718d1fd0477123139e8",
          "sha1": "3ff0a020b78a4b9abb5df056f38227f0d8d72871",
          "md5": "0ef9485a62a976c717ee8aff95c5a92c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.0.2.jar",
          "url": "customtransformplugin-1.0.2.jar",
          "size": 33055,
          "sha512": "15ac43ef815cdd44a7eec7865b75ea66bf21633182d74a02a1e0d8cdc15d81fd9184342d64cb80e3f07f319f7447630ac9440af4b6903d1bd577a0405ae7d418",
          "sha256": "3a386229708bc8a9f0beab42539cc1dc50d284dc483c9718d1fd0477123139e8",
          "sha1": "3ff0a020b78a4b9abb5df056f38227f0d8d72871",
          "md5": "0ef9485a62a976c717ee8aff95c5a92c"
        }
      ]
    }
  ]
}
