{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dream",
    "module": "customtransformplugin",
    "version": "1.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.5.7.jar",
          "url": "customtransformplugin-1.5.7.jar",
          "size": 14094,
          "sha512": "f55fbb6223c6f8d94b4abc1e5a7bd99fdd99ecce337a580d1e63ddf34e6cae97a54bd26906db90075dce9543d549ae1b4e23a0f4404f374f246662c7a4b371f6",
          "sha256": "bb55c2cdaf1ea007b24bb31f9797facd60ac36f8366e31c49d0a58a8de46e829",
          "sha1": "ce7d09cb8c35852b94f46f841876b423bf8ddb60",
          "md5": "1c89e866a1f7a1b7fcca518ec510b4cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.5.7.jar",
          "url": "customtransformplugin-1.5.7.jar",
          "size": 14094,
          "sha512": "f55fbb6223c6f8d94b4abc1e5a7bd99fdd99ecce337a580d1e63ddf34e6cae97a54bd26906db90075dce9543d549ae1b4e23a0f4404f374f246662c7a4b371f6",
          "sha256": "bb55c2cdaf1ea007b24bb31f9797facd60ac36f8366e31c49d0a58a8de46e829",
          "sha1": "ce7d09cb8c35852b94f46f841876b423bf8ddb60",
          "md5": "1c89e866a1f7a1b7fcca518ec510b4cb"
        }
      ]
    }
  ]
}
