{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.1.5.jar",
          "url": "customtransformplugin-1.1.5.jar",
          "size": 38361,
          "sha512": "5cb4ae92da48d67f216c8cafb04a5dc850f0c24314e0855b4c3100d202b860d5f3da680702ae79e8a663e3c477cf773aca8ab589814b2473ec97e3f90d104634",
          "sha256": "61db09de57a25fba1b660f74e33e1ac138c9f9832c943f18ccb8736851ec0533",
          "sha1": "d9396fef01c58076a917fbc33f4bcc8b43ba2e46",
          "md5": "48e02325ae7715fd26a1c4e4d8cf7d8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.1.5.jar",
          "url": "customtransformplugin-1.1.5.jar",
          "size": 38361,
          "sha512": "5cb4ae92da48d67f216c8cafb04a5dc850f0c24314e0855b4c3100d202b860d5f3da680702ae79e8a663e3c477cf773aca8ab589814b2473ec97e3f90d104634",
          "sha256": "61db09de57a25fba1b660f74e33e1ac138c9f9832c943f18ccb8736851ec0533",
          "sha1": "d9396fef01c58076a917fbc33f4bcc8b43ba2e46",
          "md5": "48e02325ae7715fd26a1c4e4d8cf7d8c"
        }
      ]
    }
  ]
}
