{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.2.4.jar",
          "url": "customtransformplugin-1.2.4.jar",
          "size": 48775,
          "sha512": "c92e7eb1604dc273aae09704d2712895a8f82a17e6a87bdc241034100415abcba631fad6f721abb652b897b8379d6d8a5c77c084ce4e3c0cef787a0402ba1455",
          "sha256": "0e7c393aa7e29acf57da9fec638c136d97d8c9a606ad5743f9858c8c2c872c74",
          "sha1": "b2a286433d371e81b6d0e35cb509ecee6e2c44b3",
          "md5": "ebad265c7205ea68712b256bf71f6f3a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.2.4.jar",
          "url": "customtransformplugin-1.2.4.jar",
          "size": 48775,
          "sha512": "c92e7eb1604dc273aae09704d2712895a8f82a17e6a87bdc241034100415abcba631fad6f721abb652b897b8379d6d8a5c77c084ce4e3c0cef787a0402ba1455",
          "sha256": "0e7c393aa7e29acf57da9fec638c136d97d8c9a606ad5743f9858c8c2c872c74",
          "sha1": "b2a286433d371e81b6d0e35cb509ecee6e2c44b3",
          "md5": "ebad265c7205ea68712b256bf71f6f3a"
        }
      ]
    }
  ]
}
