{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.2.1.jar",
          "url": "customtransformplugin-1.2.1.jar",
          "size": 48685,
          "sha512": "2943137a042aec58a9d477922d7152c2985ee36f5abfb06afb1bbca18c02018d3ac4700ea7704f8e0a73c6fa90a2bf56e57ccc7b2971436ffdf7c01285d1d46f",
          "sha256": "73ee824667ba5a4f99b0d4f15b8c23d02af7d80bb21d97506890d1c25f78f371",
          "sha1": "3ac0abf6f49d547e115190f6a8585f7c03a22ee8",
          "md5": "9d02ebf149a32d6bc2b441b91ddf07c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.2.1.jar",
          "url": "customtransformplugin-1.2.1.jar",
          "size": 48685,
          "sha512": "2943137a042aec58a9d477922d7152c2985ee36f5abfb06afb1bbca18c02018d3ac4700ea7704f8e0a73c6fa90a2bf56e57ccc7b2971436ffdf7c01285d1d46f",
          "sha256": "73ee824667ba5a4f99b0d4f15b8c23d02af7d80bb21d97506890d1c25f78f371",
          "sha1": "3ac0abf6f49d547e115190f6a8585f7c03a22ee8",
          "md5": "9d02ebf149a32d6bc2b441b91ddf07c3"
        }
      ]
    }
  ]
}
