{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.2.0.jar",
          "url": "customtransformplugin-1.2.0.jar",
          "size": 48595,
          "sha512": "3642481492b8e3343e3f663b97d9fc04b39710e3d0290e61f5a6d0eb9f35f2ae62d9558ee6ef0336e2f4d0fdfc876560da55a77d4f175f626ab01818429f6609",
          "sha256": "36babcaebe8a93d6790fa84482dd24b0f2bfda3f8f73b262fa332e6802fd266d",
          "sha1": "5c697aea97359b17b57b63a8a3d557bd6f85e31c",
          "md5": "a61ce63771113b0d1996712ec6282fda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.2.0.jar",
          "url": "customtransformplugin-1.2.0.jar",
          "size": 48595,
          "sha512": "3642481492b8e3343e3f663b97d9fc04b39710e3d0290e61f5a6d0eb9f35f2ae62d9558ee6ef0336e2f4d0fdfc876560da55a77d4f175f626ab01818429f6609",
          "sha256": "36babcaebe8a93d6790fa84482dd24b0f2bfda3f8f73b262fa332e6802fd266d",
          "sha1": "5c697aea97359b17b57b63a8a3d557bd6f85e31c",
          "md5": "a61ce63771113b0d1996712ec6282fda"
        }
      ]
    }
  ]
}
