{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.2.2.jar",
          "url": "customtransformplugin-1.2.2.jar",
          "size": 48832,
          "sha512": "2a83bb2da046ff0534f9d5016f6ecbd3726dee329f1eefdecc4de05e002d9a1151afb554d32ee2ca27615fa1644ccc112226328f104dcef0e844334f946d07d2",
          "sha256": "962781b94d6ce818cc1e8ce2fc52beaaa2eba3d0095693fe7a364c0abdaa69b5",
          "sha1": "d4b57e695631a8428b99ecd6a8dcb9fa57aef957",
          "md5": "226d46ba88d7be69dc124505baafd2be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.2.2.jar",
          "url": "customtransformplugin-1.2.2.jar",
          "size": 48832,
          "sha512": "2a83bb2da046ff0534f9d5016f6ecbd3726dee329f1eefdecc4de05e002d9a1151afb554d32ee2ca27615fa1644ccc112226328f104dcef0e844334f946d07d2",
          "sha256": "962781b94d6ce818cc1e8ce2fc52beaaa2eba3d0095693fe7a364c0abdaa69b5",
          "sha1": "d4b57e695631a8428b99ecd6a8dcb9fa57aef957",
          "md5": "226d46ba88d7be69dc124505baafd2be"
        }
      ]
    }
  ]
}
