{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.3.6.jar",
          "url": "customtransformplugin-1.3.6.jar",
          "size": 50063,
          "sha512": "f4ecbc46716a14de9630f62ff034860159c53f6ed169c52a0c632029c69975584782e46b26393a247b942bfef8604530afa6faaa508f951cdf3908a10a319cab",
          "sha256": "2cc082d54146bb9db9db3c2c21f7077745db0fecbae5ce2c5de90c14e60855f6",
          "sha1": "61bf29380efe878292fdf8cc365eb093b1b36d8b",
          "md5": "5717ec0b6cdab51c24b853ae6d164cfb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.3.6.jar",
          "url": "customtransformplugin-1.3.6.jar",
          "size": 50063,
          "sha512": "f4ecbc46716a14de9630f62ff034860159c53f6ed169c52a0c632029c69975584782e46b26393a247b942bfef8604530afa6faaa508f951cdf3908a10a319cab",
          "sha256": "2cc082d54146bb9db9db3c2c21f7077745db0fecbae5ce2c5de90c14e60855f6",
          "sha1": "61bf29380efe878292fdf8cc365eb093b1b36d8b",
          "md5": "5717ec0b6cdab51c24b853ae6d164cfb"
        }
      ]
    }
  ]
}
