{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.3.1.jar",
          "url": "customtransformplugin-1.3.1.jar",
          "size": 49870,
          "sha512": "03528498bbde22109749debd2b1b0e0e7d5198f793b50df2526b6cf1040298b3b29074ceb9adc2e70669187c60430b7911ba31c6d7f94936a6c3893bc0c37efa",
          "sha256": "31db65c385ee4f00b49de706aead40243721e737ad03736f8f473df0002a3a11",
          "sha1": "138d12b3d684ec829cca7cadd96759678b6ac06e",
          "md5": "49aee65eebc98576d1b18894081e8661"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.3.1.jar",
          "url": "customtransformplugin-1.3.1.jar",
          "size": 49870,
          "sha512": "03528498bbde22109749debd2b1b0e0e7d5198f793b50df2526b6cf1040298b3b29074ceb9adc2e70669187c60430b7911ba31c6d7f94936a6c3893bc0c37efa",
          "sha256": "31db65c385ee4f00b49de706aead40243721e737ad03736f8f473df0002a3a11",
          "sha1": "138d12b3d684ec829cca7cadd96759678b6ac06e",
          "md5": "49aee65eebc98576d1b18894081e8661"
        }
      ]
    }
  ]
}
