{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.3.2.jar",
          "url": "customtransformplugin-1.3.2.jar",
          "size": 49925,
          "sha512": "5a78ab5ce0775e4132b9b78ea30835c4c7ba3ba93448eb57d717e07a75c7e1f013d1d9cb7d14b7faa53a44a595dda61a83aabdae23510d06687726ef8e647593",
          "sha256": "9b8f8cf57168a292debfd20e1c8bf5fb26ba62c95381a8f7f4d37d2804e764fa",
          "sha1": "d9ada2a6c5555384cf3160d6ad5dedff9b2874d1",
          "md5": "a5700147d8965600939571797dd98cb9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.3.2.jar",
          "url": "customtransformplugin-1.3.2.jar",
          "size": 49925,
          "sha512": "5a78ab5ce0775e4132b9b78ea30835c4c7ba3ba93448eb57d717e07a75c7e1f013d1d9cb7d14b7faa53a44a595dda61a83aabdae23510d06687726ef8e647593",
          "sha256": "9b8f8cf57168a292debfd20e1c8bf5fb26ba62c95381a8f7f4d37d2804e764fa",
          "sha1": "d9ada2a6c5555384cf3160d6ad5dedff9b2874d1",
          "md5": "a5700147d8965600939571797dd98cb9"
        }
      ]
    }
  ]
}
