{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.3.4.jar",
          "url": "customtransformplugin-1.3.4.jar",
          "size": 49968,
          "sha512": "f2559136d313fd00363befc7d1c1541e591757286e7982bfd51661dc5e0fb7f094fc0cc582c93b9faf21037c53751c19610829b761c926cca5752903ff4c35cb",
          "sha256": "fea62acc5b1305fddb422d38f80acda271727d31d2058ca8c20e3da98592afbd",
          "sha1": "e7d61216f59120857c589162d24989dd162cb7d6",
          "md5": "ac76505852c166c40edad702ed8bdbae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.3.4.jar",
          "url": "customtransformplugin-1.3.4.jar",
          "size": 49968,
          "sha512": "f2559136d313fd00363befc7d1c1541e591757286e7982bfd51661dc5e0fb7f094fc0cc582c93b9faf21037c53751c19610829b761c926cca5752903ff4c35cb",
          "sha256": "fea62acc5b1305fddb422d38f80acda271727d31d2058ca8c20e3da98592afbd",
          "sha1": "e7d61216f59120857c589162d24989dd162cb7d6",
          "md5": "ac76505852c166c40edad702ed8bdbae"
        }
      ]
    }
  ]
}
