{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.0.3.jar",
          "url": "customtransformplugin-1.0.3.jar",
          "size": 33370,
          "sha512": "5574e16aec350e8ee05b48cb09a26691d1d53b13a6f67d14a42ae9469889ada7b79f04d0ca688930db43e461ec079a12c45415846422955bd1d5125585c0e530",
          "sha256": "a4d754065fb49f713e6339bfc03911a4bb129af24b53c57d452a50a4052b2785",
          "sha1": "d59e3f5e53d53872204488e9a00774ac7500b8b6",
          "md5": "ca10e5241b4e877cc79a6fe5bf53afd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.0.3.jar",
          "url": "customtransformplugin-1.0.3.jar",
          "size": 33370,
          "sha512": "5574e16aec350e8ee05b48cb09a26691d1d53b13a6f67d14a42ae9469889ada7b79f04d0ca688930db43e461ec079a12c45415846422955bd1d5125585c0e530",
          "sha256": "a4d754065fb49f713e6339bfc03911a4bb129af24b53c57d452a50a4052b2785",
          "sha1": "d59e3f5e53d53872204488e9a00774ac7500b8b6",
          "md5": "ca10e5241b4e877cc79a6fe5bf53afd6"
        }
      ]
    }
  ]
}
