{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dream",
    "module": "customtransformplugin",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.6.0.jar",
          "url": "customtransformplugin-1.6.0.jar",
          "size": 13953,
          "sha512": "0e79750480409c72dbab67f22bee3c1c97e510ebec8d6219306aa81d9d0105cfebf469044dd66834b4b8409da08b5d07cad615f992760faeb342b013ed420479",
          "sha256": "24db025ee50d36dda9f456e1b1fa4729857859519a848be07a42f0f2f0b73347",
          "sha1": "24115f71f5e43d79a541f9f55d6b7d634f94a5d5",
          "md5": "11d20dd7894f20eda31b52ef87fe6ea5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.6.0.jar",
          "url": "customtransformplugin-1.6.0.jar",
          "size": 13953,
          "sha512": "0e79750480409c72dbab67f22bee3c1c97e510ebec8d6219306aa81d9d0105cfebf469044dd66834b4b8409da08b5d07cad615f992760faeb342b013ed420479",
          "sha256": "24db025ee50d36dda9f456e1b1fa4729857859519a848be07a42f0f2f0b73347",
          "sha1": "24115f71f5e43d79a541f9f55d6b7d634f94a5d5",
          "md5": "11d20dd7894f20eda31b52ef87fe6ea5"
        }
      ]
    }
  ]
}
