{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.3.0.jar",
          "url": "customtransformplugin-1.3.0.jar",
          "size": 50384,
          "sha512": "78cefc283b625848595117e8bba70f8358439ba25bcdb118dfd16526f85475ccd7e75eb43e5de2bd68f0d4c890bf41543bf4e11f016d9200e2f5f24bcab7146a",
          "sha256": "a65598a6ecc53b895554742f3158fd7bf461ea6134b269426b84f8b2a249891f",
          "sha1": "22becedb95f45b9e9bdd7c2ce8f0d077580dab35",
          "md5": "1b9fc4607e0bbd461daa3a226fb6a333"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.3.0.jar",
          "url": "customtransformplugin-1.3.0.jar",
          "size": 50384,
          "sha512": "78cefc283b625848595117e8bba70f8358439ba25bcdb118dfd16526f85475ccd7e75eb43e5de2bd68f0d4c890bf41543bf4e11f016d9200e2f5f24bcab7146a",
          "sha256": "a65598a6ecc53b895554742f3158fd7bf461ea6134b269426b84f8b2a249891f",
          "sha1": "22becedb95f45b9e9bdd7c2ce8f0d077580dab35",
          "md5": "1b9fc4607e0bbd461daa3a226fb6a333"
        }
      ]
    }
  ]
}
