{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dream",
    "module": "customtransformplugin",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.6.6.jar",
          "url": "customtransformplugin-1.6.6.jar",
          "size": 16265,
          "sha512": "25058af173ab028ca0058bcbe7d732c1b77d1c3051855ae61704ae7ac5264ed3ab5eeabcbe6ccb22d450030391ad4ff257f8af2908372ddda0f81f5c462229cf",
          "sha256": "e6eb3c220976dd942b77955328a3bcc55108865afcf10b85392e7ddac5c7d947",
          "sha1": "1b8ec3dcab0c026520cda84ae6df33c65e96a9d1",
          "md5": "6bc933d2001c34fc7144e8dfdfc88a84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.6.6.jar",
          "url": "customtransformplugin-1.6.6.jar",
          "size": 16265,
          "sha512": "25058af173ab028ca0058bcbe7d732c1b77d1c3051855ae61704ae7ac5264ed3ab5eeabcbe6ccb22d450030391ad4ff257f8af2908372ddda0f81f5c462229cf",
          "sha256": "e6eb3c220976dd942b77955328a3bcc55108865afcf10b85392e7ddac5c7d947",
          "sha1": "1b8ec3dcab0c026520cda84ae6df33c65e96a9d1",
          "md5": "6bc933d2001c34fc7144e8dfdfc88a84"
        }
      ]
    }
  ]
}
