{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.0.0.jar",
          "url": "customtransformplugin-1.0.0.jar",
          "size": 28990,
          "sha512": "96fdff2d71adbd15e13ea61664755dfb91d7e683f48b61cf9c1bc82c41fa36f55ad8756167d0d6e233d6b7aa6b8e268e89017bb66e20c4072762d9390e0a62af",
          "sha256": "4069abc9bfe6e67c258f42d6eeb76907e155d47934f9faed38c3fdac58f08d50",
          "sha1": "ad5dab4e19b61b2096e3420ac5f7e5594bcb55d8",
          "md5": "41f2ea385aaa57eacc87556cef31ccee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.0.0.jar",
          "url": "customtransformplugin-1.0.0.jar",
          "size": 28990,
          "sha512": "96fdff2d71adbd15e13ea61664755dfb91d7e683f48b61cf9c1bc82c41fa36f55ad8756167d0d6e233d6b7aa6b8e268e89017bb66e20c4072762d9390e0a62af",
          "sha256": "4069abc9bfe6e67c258f42d6eeb76907e155d47934f9faed38c3fdac58f08d50",
          "sha1": "ad5dab4e19b61b2096e3420ac5f7e5594bcb55d8",
          "md5": "41f2ea385aaa57eacc87556cef31ccee"
        }
      ]
    }
  ]
}
