{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.0.1.jar",
          "url": "customtransformplugin-1.0.1.jar",
          "size": 32804,
          "sha512": "54645ea555d0ca556e16e9aa81240fee552af02bf0bf462a3064de0c37a3bf806cea6717612c4f6f059207e0aa5b4f269a8c80ad8efc0b25e355fc5a69c4cf5f",
          "sha256": "1b227193de3a257aa9bbd42d1220d5561957c301707960ab48923d63047bb100",
          "sha1": "28ef9d77ee5ff8785d968375a6f517dfa466e194",
          "md5": "458fc59a25f5310807b6a943ce3ec507"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.0.1.jar",
          "url": "customtransformplugin-1.0.1.jar",
          "size": 32804,
          "sha512": "54645ea555d0ca556e16e9aa81240fee552af02bf0bf462a3064de0c37a3bf806cea6717612c4f6f059207e0aa5b4f269a8c80ad8efc0b25e355fc5a69c4cf5f",
          "sha256": "1b227193de3a257aa9bbd42d1220d5561957c301707960ab48923d63047bb100",
          "sha1": "28ef9d77ee5ff8785d968375a6f517dfa466e194",
          "md5": "458fc59a25f5310807b6a943ce3ec507"
        }
      ]
    }
  ]
}
