{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dream",
    "module": "customtransformplugin",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.5.2.jar",
          "url": "customtransformplugin-1.5.2.jar",
          "size": 13916,
          "sha512": "9461715e1db2105cf6e6fd1a00862edd9dade859caa06fc1199c861c0ee6b4307a548b9a7781cfa8f7759c8e1ccc15456f39a6db62c47d3fbe8ce88189c65b46",
          "sha256": "76cbdc2d4b47623fb1054014a60c7958f9164bbaf82db85888b6ab4bd58e62a7",
          "sha1": "1e12732c50a2c5188ea5b9a2d751d3de6409f008",
          "md5": "d167adb066a35360c1aafe9e96e984c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.5.2.jar",
          "url": "customtransformplugin-1.5.2.jar",
          "size": 13916,
          "sha512": "9461715e1db2105cf6e6fd1a00862edd9dade859caa06fc1199c861c0ee6b4307a548b9a7781cfa8f7759c8e1ccc15456f39a6db62c47d3fbe8ce88189c65b46",
          "sha256": "76cbdc2d4b47623fb1054014a60c7958f9164bbaf82db85888b6ab4bd58e62a7",
          "sha1": "1e12732c50a2c5188ea5b9a2d751d3de6409f008",
          "md5": "d167adb066a35360c1aafe9e96e984c7"
        }
      ]
    }
  ]
}
