{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.2.5.jar",
          "url": "customtransformplugin-1.2.5.jar",
          "size": 48887,
          "sha512": "19e48f3e9c54d77f978e7d548e823adb1acfb20748a1d1765a13e6202fa8e9784712360ced837cc54f1f9d1eeee21d8a639ed0d40078b9d23f33ffdc02079e2e",
          "sha256": "80b4b3044550d165de226ca66cc9b35ed5c34d67d95a5e42968d74d30fd0b5d3",
          "sha1": "d30e5a918b1f38fb5c8eef78c80766c7468f2d83",
          "md5": "c1305b616a04e16157d0edf7294df26e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.2.5.jar",
          "url": "customtransformplugin-1.2.5.jar",
          "size": 48887,
          "sha512": "19e48f3e9c54d77f978e7d548e823adb1acfb20748a1d1765a13e6202fa8e9784712360ced837cc54f1f9d1eeee21d8a639ed0d40078b9d23f33ffdc02079e2e",
          "sha256": "80b4b3044550d165de226ca66cc9b35ed5c34d67d95a5e42968d74d30fd0b5d3",
          "sha1": "d30e5a918b1f38fb5c8eef78c80766c7468f2d83",
          "md5": "c1305b616a04e16157d0edf7294df26e"
        }
      ]
    }
  ]
}
