{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.3.3.jar",
          "url": "customtransformplugin-1.3.3.jar",
          "size": 49952,
          "sha512": "e6d309d3cf9899bf9c5fd46bef9b5bfd2426c1af751f2e1b737c227566536f8f5bcac496eb8d93620f9d33c8773834ec6826a545243a5fcca2b8e81bccb432ca",
          "sha256": "600b5e6db4f88940ce030ef3df41bcfa53be5c1db548612537b79570c6e49741",
          "sha1": "28e1bccafd70b75cd7ae602e0ab9bb0e339226f9",
          "md5": "d2b9a947cd2a66c02494d6cf87176e66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.3.3.jar",
          "url": "customtransformplugin-1.3.3.jar",
          "size": 49952,
          "sha512": "e6d309d3cf9899bf9c5fd46bef9b5bfd2426c1af751f2e1b737c227566536f8f5bcac496eb8d93620f9d33c8773834ec6826a545243a5fcca2b8e81bccb432ca",
          "sha256": "600b5e6db4f88940ce030ef3df41bcfa53be5c1db548612537b79570c6e49741",
          "sha1": "28e1bccafd70b75cd7ae602e0ab9bb0e339226f9",
          "md5": "d2b9a947cd2a66c02494d6cf87176e66"
        }
      ]
    }
  ]
}
