{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.3.8.jar",
          "url": "customtransformplugin-1.3.8.jar",
          "size": 48640,
          "sha512": "255b8f6f4e9a5e9fc0fd41d86cf1b6885c37a393a8cdc4e7c697354ca84426a90a912b861b6ade5f499f188db0fb029faaa604b349c820e9ee30635cd20af3ca",
          "sha256": "dcfb6bae0a8b4195532b8cd6d131a8ff128983f03d5d61afeb412a89e81b4ff6",
          "sha1": "3de4d66d14fd793066947ade2da1dfb0c48018bc",
          "md5": "44ad942ab666e6c0931d3482ad703a7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.3.8.jar",
          "url": "customtransformplugin-1.3.8.jar",
          "size": 48640,
          "sha512": "255b8f6f4e9a5e9fc0fd41d86cf1b6885c37a393a8cdc4e7c697354ca84426a90a912b861b6ade5f499f188db0fb029faaa604b349c820e9ee30635cd20af3ca",
          "sha256": "dcfb6bae0a8b4195532b8cd6d131a8ff128983f03d5d61afeb412a89e81b4ff6",
          "sha1": "3de4d66d14fd793066947ade2da1dfb0c48018bc",
          "md5": "44ad942ab666e6c0931d3482ad703a7b"
        }
      ]
    }
  ]
}
