{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dream",
    "module": "customtransformplugin",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.7.5.jar",
          "url": "customtransformplugin-1.7.5.jar",
          "size": 18625,
          "sha512": "7960880f807256d81f83954b1b0411b4ce8ceaf52bb476e4fdb75c3d5316f84ccce0189a1f9da685a8306e85c7a89c56b3e6cb5c1f989977517c86e4a5b3c3f4",
          "sha256": "27d8b8fbc688098705fdb58bf1b1392b30e5eaf18894911e8b71aa583caa42d7",
          "sha1": "9cfff6ad682931bb29e23f0d1c5da5c8a2ed8677",
          "md5": "2ee99d408bbff04ac474a25af6ad5b2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.7.5.jar",
          "url": "customtransformplugin-1.7.5.jar",
          "size": 18625,
          "sha512": "7960880f807256d81f83954b1b0411b4ce8ceaf52bb476e4fdb75c3d5316f84ccce0189a1f9da685a8306e85c7a89c56b3e6cb5c1f989977517c86e4a5b3c3f4",
          "sha256": "27d8b8fbc688098705fdb58bf1b1392b30e5eaf18894911e8b71aa583caa42d7",
          "sha1": "9cfff6ad682931bb29e23f0d1c5da5c8a2ed8677",
          "md5": "2ee99d408bbff04ac474a25af6ad5b2f"
        }
      ]
    }
  ]
}
