{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dream",
    "module": "customtransformplugin",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.5.1.jar",
          "url": "customtransformplugin-1.5.1.jar",
          "size": 13349,
          "sha512": "1165d847794946d712c74e7bc6d143795ba65e216ea661274ff01ff85d00222b44eed49e6e8841a4d067f3bae4d97f550cff177ebc80a82b66efee927ccc7665",
          "sha256": "2cf31ab49fdcdfbf17e6d4980fca2846826ff585741805cfc1251b7013207a44",
          "sha1": "c9db680cfd43b4aec3fdbadca0f088da6fcc0b2e",
          "md5": "4c61c971ad5d01788c96efc81d5aa95b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.5.1.jar",
          "url": "customtransformplugin-1.5.1.jar",
          "size": 13349,
          "sha512": "1165d847794946d712c74e7bc6d143795ba65e216ea661274ff01ff85d00222b44eed49e6e8841a4d067f3bae4d97f550cff177ebc80a82b66efee927ccc7665",
          "sha256": "2cf31ab49fdcdfbf17e6d4980fca2846826ff585741805cfc1251b7013207a44",
          "sha1": "c9db680cfd43b4aec3fdbadca0f088da6fcc0b2e",
          "md5": "4c61c971ad5d01788c96efc81d5aa95b"
        }
      ]
    }
  ]
}
