{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.3.5.jar",
          "url": "customtransformplugin-1.3.5.jar",
          "size": 49970,
          "sha512": "4578029a73d6e5cd8f12c9d2958669bba8757ebd7c7558c72b853bd7a7ca4245ebd28b2fccbca5504843e893746aa1bcd27a025363f08e46dfc6aa238763db78",
          "sha256": "e7caad62caa5bfe7f453fef7120588a27625c6b2d0afa4c3096c7a84a09dfd9f",
          "sha1": "e3f22ed79de6b08c23cf726d9bb1687a04660320",
          "md5": "b2c4d6f4d35f93f6ee28360c634ad0fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.3.5.jar",
          "url": "customtransformplugin-1.3.5.jar",
          "size": 49970,
          "sha512": "4578029a73d6e5cd8f12c9d2958669bba8757ebd7c7558c72b853bd7a7ca4245ebd28b2fccbca5504843e893746aa1bcd27a025363f08e46dfc6aa238763db78",
          "sha256": "e7caad62caa5bfe7f453fef7120588a27625c6b2d0afa4c3096c7a84a09dfd9f",
          "sha1": "e3f22ed79de6b08c23cf726d9bb1687a04660320",
          "md5": "b2c4d6f4d35f93f6ee28360c634ad0fe"
        }
      ]
    }
  ]
}
