{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.1.2.jar",
          "url": "customtransformplugin-1.1.2.jar",
          "size": 37339,
          "sha512": "dc66a26a5ae8de1684bbd8fe6a08cb9cd266bb1a7a3beff728e6059a05beab948227a6f8f10805aa453539efc15d8e68f3feccdf4307d60ce08be2ae618033df",
          "sha256": "c2e7308f8e7b2885770025873b7cb30163d4b59e9bf23cef3077c8a5893caa97",
          "sha1": "31c4efb5ec0f9f7dd9304f59a6c891876cf5f510",
          "md5": "c5c834e6ce5308f40964fdde0e4c721a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.1.2.jar",
          "url": "customtransformplugin-1.1.2.jar",
          "size": 37339,
          "sha512": "dc66a26a5ae8de1684bbd8fe6a08cb9cd266bb1a7a3beff728e6059a05beab948227a6f8f10805aa453539efc15d8e68f3feccdf4307d60ce08be2ae618033df",
          "sha256": "c2e7308f8e7b2885770025873b7cb30163d4b59e9bf23cef3077c8a5893caa97",
          "sha1": "31c4efb5ec0f9f7dd9304f59a6c891876cf5f510",
          "md5": "c5c834e6ce5308f40964fdde0e4c721a"
        }
      ]
    }
  ]
}
