{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.2.8.jar",
          "url": "customtransformplugin-1.2.8.jar",
          "size": 50309,
          "sha512": "06bc46a78ac74532ad339bc5d9fea7788af62310551eb135d8aa60758915e6776819827a26ae49f3f94ebe9dfe8a67726f839b53900b0d07744c44e77c31c4b3",
          "sha256": "238495f8b2bb88fed0bc093e7bdb405bce19d422e11b131abe67db26a7ef2ff9",
          "sha1": "d6bc985bf60b8e9aa248566c9a4e20b2d207796c",
          "md5": "ecf5657ab430c7cb0126a31640602127"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.2.8.jar",
          "url": "customtransformplugin-1.2.8.jar",
          "size": 50309,
          "sha512": "06bc46a78ac74532ad339bc5d9fea7788af62310551eb135d8aa60758915e6776819827a26ae49f3f94ebe9dfe8a67726f839b53900b0d07744c44e77c31c4b3",
          "sha256": "238495f8b2bb88fed0bc093e7bdb405bce19d422e11b131abe67db26a7ef2ff9",
          "sha1": "d6bc985bf60b8e9aa248566c9a4e20b2d207796c",
          "md5": "ecf5657ab430c7cb0126a31640602127"
        }
      ]
    }
  ]
}
