{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.3.9.jar",
          "url": "customtransformplugin-1.3.9.jar",
          "size": 48640,
          "sha512": "e9990792aa2f78039e408fa5f809c00ea74477cf00d1b3f146b4aa29e74e6d93a252a42245f93fdfbaf48bbffc6d93a30f390a0827ec201022ff388dd408b951",
          "sha256": "e87ae22997098abae5815ee02664eaa975dd541101fbe06604457459db950cad",
          "sha1": "c52e190c9d3a395f3cf49c6b712b43e2c8248696",
          "md5": "eb940c3e578810e4c529560f937d754f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.3.9.jar",
          "url": "customtransformplugin-1.3.9.jar",
          "size": 48640,
          "sha512": "e9990792aa2f78039e408fa5f809c00ea74477cf00d1b3f146b4aa29e74e6d93a252a42245f93fdfbaf48bbffc6d93a30f390a0827ec201022ff388dd408b951",
          "sha256": "e87ae22997098abae5815ee02664eaa975dd541101fbe06604457459db950cad",
          "sha1": "c52e190c9d3a395f3cf49c6b712b43e2c8248696",
          "md5": "eb940c3e578810e4c529560f937d754f"
        }
      ]
    }
  ]
}
