{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dream",
    "module": "customtransformplugin",
    "version": "1.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.5.9.jar",
          "url": "customtransformplugin-1.5.9.jar",
          "size": 13953,
          "sha512": "34b7ab3df48999790278683f7d332d7261d0e796a810bc4b875bc80d6010fe593194ae6716117f758dfdea6665b9d237a5e80fcbac1c4c7568b5842bdcf775da",
          "sha256": "f9c9cf7b55b8632f4f14950668e5a0394b82fa96fb17abaceeb7b7f1ee50867a",
          "sha1": "6c6b62c5b1597f27fd6c0e300372c873b92aa990",
          "md5": "cd4bad84c505fca5b50604e76adc0d7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.5.9.jar",
          "url": "customtransformplugin-1.5.9.jar",
          "size": 13953,
          "sha512": "34b7ab3df48999790278683f7d332d7261d0e796a810bc4b875bc80d6010fe593194ae6716117f758dfdea6665b9d237a5e80fcbac1c4c7568b5842bdcf775da",
          "sha256": "f9c9cf7b55b8632f4f14950668e5a0394b82fa96fb17abaceeb7b7f1ee50867a",
          "sha1": "6c6b62c5b1597f27fd6c0e300372c873b92aa990",
          "md5": "cd4bad84c505fca5b50604e76adc0d7f"
        }
      ]
    }
  ]
}
