{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.0.5.jar",
          "url": "customtransformplugin-1.0.5.jar",
          "size": 33494,
          "sha512": "d9ac545d407429efd36699f6fc453185ee8f2963c3f1bfc15fd99f3170e755f7fa5712f559f35e72911440fd9297bd46026bd736e2b3e691514f56ea21c930ab",
          "sha256": "fde93a68766911119be5a2f44b9197f19bb5b17a62e02b1a737c43c86ebf35ce",
          "sha1": "a5e83f65dc20e285145fcc1993d87d617b967c10",
          "md5": "6527472df3538684c2fe4a6aaafffa44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.0.5.jar",
          "url": "customtransformplugin-1.0.5.jar",
          "size": 33494,
          "sha512": "d9ac545d407429efd36699f6fc453185ee8f2963c3f1bfc15fd99f3170e755f7fa5712f559f35e72911440fd9297bd46026bd736e2b3e691514f56ea21c930ab",
          "sha256": "fde93a68766911119be5a2f44b9197f19bb5b17a62e02b1a737c43c86ebf35ce",
          "sha1": "a5e83f65dc20e285145fcc1993d87d617b967c10",
          "md5": "6527472df3538684c2fe4a6aaafffa44"
        }
      ]
    }
  ]
}
