include:
  classes:
    - com.dream.gradletransformdemo
    # - other/package
  methods:
    - insertByGT
    - updateByGT
    - addByGT
    - deleteByGT
    # - otherMethod
  systemMethods:
    - println
    # - otherSystemMethod