{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dream",
    "module": "customtransformplugin",
    "version": "1.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.7.4.jar",
          "url": "customtransformplugin-1.7.4.jar",
          "size": 17878,
          "sha512": "2c10d8840e17055551a92d4793ff87b7af9fe29bf80af6edacb54e2eabbb3039a542d1943d9a3854866e1c5f3d971fae94975f0036f73532419133beeabf7959",
          "sha256": "e78b61de52df7949c43788998215fbc2a287e65631527cee19eb976de8433ae1",
          "sha1": "7eff70a6501e84494eb0d20c0618644cae9da024",
          "md5": "fd617b4a3a7afaeadfbdec770e894803"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.7.4.jar",
          "url": "customtransformplugin-1.7.4.jar",
          "size": 17878,
          "sha512": "2c10d8840e17055551a92d4793ff87b7af9fe29bf80af6edacb54e2eabbb3039a542d1943d9a3854866e1c5f3d971fae94975f0036f73532419133beeabf7959",
          "sha256": "e78b61de52df7949c43788998215fbc2a287e65631527cee19eb976de8433ae1",
          "sha1": "7eff70a6501e84494eb0d20c0618644cae9da024",
          "md5": "fd617b4a3a7afaeadfbdec770e894803"
        }
      ]
    }
  ]
}
