{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dream",
    "module": "customtransformplugin",
    "version": "1.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.6.4.jar",
          "url": "customtransformplugin-1.6.4.jar",
          "size": 13605,
          "sha512": "2efab0fc38351ea0c4680137452fe8b0c6887314bc1f8ae788e95c2f51a8658ee9cd254295b33c98f2ea0d091d40b32092aaa5110854dfc65703671a6985d4f8",
          "sha256": "0534626c7b6f6f6be9818f504be6c987358238c6268a3720add9673dcd1cbbb8",
          "sha1": "b2bf29f5ad507200679a1de75cfe2765aed3787c",
          "md5": "febc5caad3f5ab5741efa563121d65af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.6.4.jar",
          "url": "customtransformplugin-1.6.4.jar",
          "size": 13605,
          "sha512": "2efab0fc38351ea0c4680137452fe8b0c6887314bc1f8ae788e95c2f51a8658ee9cd254295b33c98f2ea0d091d40b32092aaa5110854dfc65703671a6985d4f8",
          "sha256": "0534626c7b6f6f6be9818f504be6c987358238c6268a3720add9673dcd1cbbb8",
          "sha1": "b2bf29f5ad507200679a1de75cfe2765aed3787c",
          "md5": "febc5caad3f5ab5741efa563121d65af"
        }
      ]
    }
  ]
}
