{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dream",
    "module": "customtransformplugin",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.6.9.jar",
          "url": "customtransformplugin-1.6.9.jar",
          "size": 17523,
          "sha512": "46071c1ca6d0b204a2b31284301c79d33123b4461b3360fa0f0d23545d26376b96ece6a2614221ca473d9b605fc0ec4cc4be80b09c85bff7c3fd20442b5c6115",
          "sha256": "2d24fe5d92a537f8ca476442639252c987a119d03ffa1a54c2b16c3b030b2b1f",
          "sha1": "9122d203d80e5ea0b8fd8a21d4013c0a89b67638",
          "md5": "02a4023d4984909b02c985a9b3be8b2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.6.9.jar",
          "url": "customtransformplugin-1.6.9.jar",
          "size": 17523,
          "sha512": "46071c1ca6d0b204a2b31284301c79d33123b4461b3360fa0f0d23545d26376b96ece6a2614221ca473d9b605fc0ec4cc4be80b09c85bff7c3fd20442b5c6115",
          "sha256": "2d24fe5d92a537f8ca476442639252c987a119d03ffa1a54c2b16c3b030b2b1f",
          "sha1": "9122d203d80e5ea0b8fd8a21d4013c0a89b67638",
          "md5": "02a4023d4984909b02c985a9b3be8b2c"
        }
      ]
    }
  ]
}
