{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.1.0.jar",
          "url": "customtransformplugin-1.1.0.jar",
          "size": 33762,
          "sha512": "7cdc230ccf914075ec1e47412661a2412ed5f65d0545e33d43e57576c3d7d0029d83b847b473d75f2f189608de7e9e4deab2422c1bb757d259c5cca753b29cbe",
          "sha256": "ffff7899efd8ad2e76acefa9cecb21b390325bf3fe72d5dbc0cbe2e932d5cc69",
          "sha1": "1de248557fc920e75f6463b8669cb75a19553c7e",
          "md5": "e0d743f5df202b3652663266f609dd31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.1.0.jar",
          "url": "customtransformplugin-1.1.0.jar",
          "size": 33762,
          "sha512": "7cdc230ccf914075ec1e47412661a2412ed5f65d0545e33d43e57576c3d7d0029d83b847b473d75f2f189608de7e9e4deab2422c1bb757d259c5cca753b29cbe",
          "sha256": "ffff7899efd8ad2e76acefa9cecb21b390325bf3fe72d5dbc0cbe2e932d5cc69",
          "sha1": "1de248557fc920e75f6463b8669cb75a19553c7e",
          "md5": "e0d743f5df202b3652663266f609dd31"
        }
      ]
    }
  ]
}
