{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dream",
    "module": "customtransformplugin",
    "version": "1.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.6.3.jar",
          "url": "customtransformplugin-1.6.3.jar",
          "size": 13601,
          "sha512": "b6efc24eb520a69f9d2bcb6d6fd44fd45bbcca07c3416dd9ff6a55284fe0a5a0336ab370038cf040eee1605053620df4cd8df730c6a99a916c2d736ae2c28089",
          "sha256": "357315c3a97d12fa77f9f697f09c77b28e2e0e9e963d4e6731c4167f8c2c1794",
          "sha1": "bf5e8c563f2cf148c7800ccca46760e0d8f250d7",
          "md5": "971f9d3a9a4064ddcd67bad91aacd67f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.6.3.jar",
          "url": "customtransformplugin-1.6.3.jar",
          "size": 13601,
          "sha512": "b6efc24eb520a69f9d2bcb6d6fd44fd45bbcca07c3416dd9ff6a55284fe0a5a0336ab370038cf040eee1605053620df4cd8df730c6a99a916c2d736ae2c28089",
          "sha256": "357315c3a97d12fa77f9f697f09c77b28e2e0e9e963d4e6731c4167f8c2c1794",
          "sha1": "bf5e8c563f2cf148c7800ccca46760e0d8f250d7",
          "md5": "971f9d3a9a4064ddcd67bad91aacd67f"
        }
      ]
    }
  ]
}
