{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.1.3.jar",
          "url": "customtransformplugin-1.1.3.jar",
          "size": 38140,
          "sha512": "84e913e995deab988f38c6aa018f748752c67fd47f74f7ac5ffd0a55bc138ef2ab1a7c04efff1f07347507e3fb4fd0bf1a75ce327379bd056a184000f7f324cf",
          "sha256": "20357e798f52e0a958f3194b880d715209e6feb50491396e3f6e311bcd107458",
          "sha1": "961606627f59da954bbd28070a6c104dd346c118",
          "md5": "c9612e7cfa7e208dc903e40d5df09062"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.1.3.jar",
          "url": "customtransformplugin-1.1.3.jar",
          "size": 38140,
          "sha512": "84e913e995deab988f38c6aa018f748752c67fd47f74f7ac5ffd0a55bc138ef2ab1a7c04efff1f07347507e3fb4fd0bf1a75ce327379bd056a184000f7f324cf",
          "sha256": "20357e798f52e0a958f3194b880d715209e6feb50491396e3f6e311bcd107458",
          "sha1": "961606627f59da954bbd28070a6c104dd346c118",
          "md5": "c9612e7cfa7e208dc903e40d5df09062"
        }
      ]
    }
  ]
}
