{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dream",
    "module": "customtransformplugin",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.6.1.jar",
          "url": "customtransformplugin-1.6.1.jar",
          "size": 13870,
          "sha512": "c4afeb93e622327fc58e897f73b00da3e29c4fec6709b49a166890a42f8ab7c1c8e62490832f833c3ffb074302e1abae1cfd5bd403ad204616952540f18fc9af",
          "sha256": "06f4d35d51c7de62c3e13ea4cdb89a6ce2fe5bcb807b0b52017841d69b552415",
          "sha1": "72cc2b035083498270e12d077f9bf94d7fb9e69a",
          "md5": "2badb8e45a1b52e876da867bc8e9bfd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.6.1.jar",
          "url": "customtransformplugin-1.6.1.jar",
          "size": 13870,
          "sha512": "c4afeb93e622327fc58e897f73b00da3e29c4fec6709b49a166890a42f8ab7c1c8e62490832f833c3ffb074302e1abae1cfd5bd403ad204616952540f18fc9af",
          "sha256": "06f4d35d51c7de62c3e13ea4cdb89a6ce2fe5bcb807b0b52017841d69b552415",
          "sha1": "72cc2b035083498270e12d077f9bf94d7fb9e69a",
          "md5": "2badb8e45a1b52e876da867bc8e9bfd7"
        }
      ]
    }
  ]
}
