{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.2.6.jar",
          "url": "customtransformplugin-1.2.6.jar",
          "size": 50362,
          "sha512": "941f6b6f52c7053cdb15cf802c9c535dc1adfaecc379d00be90235fcee84f7d27de8bcce8d5fefe10706fe2dbe0438ec032a1858eb9bd826f949e2d6f7b937d4",
          "sha256": "67a95574544b9cc163172a69d65c3a03209bcb24e843c9bb04ae4d3e264d984d",
          "sha1": "c161698b2bd3a52796215f5fbe2fb536525e51a2",
          "md5": "eda9f2c9c6ddccc6ae6a2919258c58b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.2.6.jar",
          "url": "customtransformplugin-1.2.6.jar",
          "size": 50362,
          "sha512": "941f6b6f52c7053cdb15cf802c9c535dc1adfaecc379d00be90235fcee84f7d27de8bcce8d5fefe10706fe2dbe0438ec032a1858eb9bd826f949e2d6f7b937d4",
          "sha256": "67a95574544b9cc163172a69d65c3a03209bcb24e843c9bb04ae4d3e264d984d",
          "sha1": "c161698b2bd3a52796215f5fbe2fb536525e51a2",
          "md5": "eda9f2c9c6ddccc6ae6a2919258c58b1"
        }
      ]
    }
  ]
}
