{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dream",
    "module": "customtransformplugin",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.6.7.jar",
          "url": "customtransformplugin-1.6.7.jar",
          "size": 16324,
          "sha512": "6dbc4601c077d81fa35fe492474ad145cb8d98ad7785bba7c23d73cbfb5e93a07c4557837bc3a0e7ce91c86a0419db6ece5ade25e3611ddaad0f9bf1bde14604",
          "sha256": "459e834d791bbfd1eb2f429a9b359317f30fa434e240fa3ae879f4845f9533d6",
          "sha1": "890e0530701a12f4a7f5557a053e207cd026935d",
          "md5": "6edf80abcde598a5eab38c6f23a53b2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.6.7.jar",
          "url": "customtransformplugin-1.6.7.jar",
          "size": 16324,
          "sha512": "6dbc4601c077d81fa35fe492474ad145cb8d98ad7785bba7c23d73cbfb5e93a07c4557837bc3a0e7ce91c86a0419db6ece5ade25e3611ddaad0f9bf1bde14604",
          "sha256": "459e834d791bbfd1eb2f429a9b359317f30fa434e240fa3ae879f4845f9533d6",
          "sha1": "890e0530701a12f4a7f5557a053e207cd026935d",
          "md5": "6edf80abcde598a5eab38c6f23a53b2c"
        }
      ]
    }
  ]
}
