{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.3.7.jar",
          "url": "customtransformplugin-1.3.7.jar",
          "size": 50140,
          "sha512": "18e453e90d9c97bd7e71e4357afb56a335911227ef734d3b660a1782c53d2580e16f7021d0ad6e11688b8f581722e964e5ea581060a2945cf83cb2f86d687765",
          "sha256": "5d77c45f7532edf9543384913ac7a05830e5634cd92d1f2949aee3175db8af4c",
          "sha1": "5778cc991376dd872c375799178ee6875bc01e6c",
          "md5": "8d531fb838f4900240566c447d41b50a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.3.7.jar",
          "url": "customtransformplugin-1.3.7.jar",
          "size": 50140,
          "sha512": "18e453e90d9c97bd7e71e4357afb56a335911227ef734d3b660a1782c53d2580e16f7021d0ad6e11688b8f581722e964e5ea581060a2945cf83cb2f86d687765",
          "sha256": "5d77c45f7532edf9543384913ac7a05830e5634cd92d1f2949aee3175db8af4c",
          "sha1": "5778cc991376dd872c375799178ee6875bc01e6c",
          "md5": "8d531fb838f4900240566c447d41b50a"
        }
      ]
    }
  ]
}
