{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.0.7.jar",
          "url": "customtransformplugin-1.0.7.jar",
          "size": 33706,
          "sha512": "2fba91113027cc9c1a0f1d288dfb02a6c94cd7b444c8c4f455b522dfddd5d119699fbd3045f307a7cc6ac7c9c73a828f1fa8de287c6383769a0a937b058cd1ae",
          "sha256": "d3d88c4a0b6b9286f41ec24979af51de1d63ae8e7fd1e479c9c412ed9b1e1845",
          "sha1": "d40a111fc6326aae0fc9724a7d4920094d8d2ee9",
          "md5": "7827c01205eb334261231817d40d6b64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.0.7.jar",
          "url": "customtransformplugin-1.0.7.jar",
          "size": 33706,
          "sha512": "2fba91113027cc9c1a0f1d288dfb02a6c94cd7b444c8c4f455b522dfddd5d119699fbd3045f307a7cc6ac7c9c73a828f1fa8de287c6383769a0a937b058cd1ae",
          "sha256": "d3d88c4a0b6b9286f41ec24979af51de1d63ae8e7fd1e479c9c412ed9b1e1845",
          "sha1": "d40a111fc6326aae0fc9724a7d4920094d8d2ee9",
          "md5": "7827c01205eb334261231817d40d6b64"
        }
      ]
    }
  ]
}
